# Generated by Django 5.1.6 on 2025-02-13 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Openacc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountnumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('photo', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.TextField()),
                ('phone', models.TextField()),
                ('address', models.TextField()),
                ('photo', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
                ('accountnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bank')),
            ],
        ),
    ]
